name: 'Query shodan internetdb'
description: 'Query shodan internetdb for an entire CIDR'
author: 'GitHub'
inputs:
  cidr:
    description: 'The CIDR range to query'

jobs:
  query:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v4

      - run: go install github.com/j3ssie/sdlookup@latest

      - name: query CIDR
        run:  echo ${{ inputs.cidr }} | sdlookup -json > $(echo ${{ inputs.cidr }} | tr / _).json


